FROM ubuntu:20.04

LABEL mainteiner = "Julissa Dominguez"
LABEL version = "v1"
LABEL description = "Base de datos sqlite3"

RUN apt-get update

RUN apt-get install -y php-fpm
RUN apt-get install -y php-sqlite3 
RUN apt-get install -y sqlite3

EXPOSE 8080